### ISSUE TITLE
Additionally cache ~/.rustup folder

### ISSUE THREAD

**Issue by alerque** [Swatinem/rust-cache#13]
Doesn't the `actions-rs/toolchain` action end up installing a toolchain in `~/.rustup` and *not* caching it? Shouldn't / couldn't that be cached by default here as well?

**Comment by Swatinem** [comment]
The toolchain action should definitely be run before the cache action, and also needs to set the selected toolchain as local override (the cache uses the `rustc` version hash as one of the keys). I should maybe document that better.

**Comment by alerque** [comment]
I'm sorry maybe I wasn't clear. I understand the ordering issue (and have my `rust-cache` action setup to run *after* my `toolchain` action), my question was about whether the Rust toolchain was even getting cached at all. The build cache and project specific stuff is being cached, but the toolchain itself doesn't seem to be. The `./.rustup` folder where the `toolchain` action stores the actual Rust installation. Or should that be the job of the `toolchain` action?

**Comment by Swatinem** [comment]
> Or should that be the job of the `toolchain` action?

I don’t think they do any caching at all, but ideally yes, the toolchain should be responsible to do that. Also, if you are using stable, and the running is halfway up-to-date, it will be a noop anyway.

Because of the ordering of the two actions, you just can’t restore any kind of rustup cache before the toolchain action runs. And without the toolchain, you don’t have a cache key to begin with.

I’m unsure what the expectation here would be?

**Comment by alerque** [comment]
> Because of the ordering of the two actions, you just can’t restore any kind of rustup cache before the toolchain action runs.

You are correct, I'm following now. I hadn't thought through *that* end of the stick. I'll mention this on the `toolchain` repo instead.
