### ISSUE TITLE
Add ability to specify multiple `target-dir`s

### ISSUE THREAD

**Issue by nicholastmosher** [Swatinem/rust-cache#24]
Hi @Swatinem thanks for rust-cache, it's very useful! I was wondering whether it's possible to specify more than one target directory to be cached. I have a project with a top-level workspace that shares one target directory, and another independent, nested workspace (used because we build for WASM targets by default there), and the nested workspace has a separate target/ directory that I don't believe gets cached by this action.

So if our folder structure looked like this:

```
project/
  Cargo.toml
  src/
  target/
  wasm-project/
    Cargo.toml
    src/
    target/
```

Then I believe only `project/target/` is getting cached, and I'm wondering if it'd be possible somehow to add multiple entries to `target-dir` so that `project/wasm-project/target/` would also be cached.

**Comment by Swatinem** [comment]
I think that should be possible indeed. Might be some effort to refactor, but I see no reason why not.

Also, I have never tried what happens if you define the cache action twice… it would probably over-clean the global cargo registery, etc.
Which reminds me. We would have to merge all the packages/versions (essentially the cargo lock) that contributed to the global registry to effectively cache that, which makes this a bit more tedious.

**Comment by nicholastmosher** [comment]
It looks like `getLockfileHash` should already incorporate all `Cargo.toml`'s and `Cargo.lock`'s since it uses the globs `**/Cargo.toml` and `**/Cargo.lock`, though tell me if you think something about this wouldn't work how I'm expecting. I think that as long as all of the directories are some descendant of cwd, it should be fine.

**Comment by Swatinem** [comment]
The cache tries to be smart, and only keep things that you *need*. so it does a `cargo metadata` in the background to determine the packages and versions it needs to keep.

**Comment by Swatinem** [comment]
This should now work with `v2`

**Comment by kaimast** [comment]
So if I have two target directories in the workspace do I write `". -> target1,target2"` or `". -> target1\n. -> target2"`?
