### ISSUE TITLE
Is possible an option to cache also build of own code?

### ISSUE THREAD

**Issue by jhg** [Swatinem/rust-cache#37]
The idea is an option default to false to improve builds as Rust compiler will have cache and only need to build the changes.

**Comment by Swatinem** [comment]
The idea is that the tradeoff to only cache dependencies is better because:
* it would only cache the first invocation when it generates a new cache key.
* with time the code will diverge more, causing longer builds.
* incremental needs a lot of disk space, and thus cache space and time to fetch & extract, lowering the benefits.

**Comment by jhg** [comment]
Thanks for the comment @Swatinem. About the first two points, I was thinking in incremental and default to false, but I guess that could be complex to do. And interesting the third point.
