### ISSUE TITLE
How to clean cache or force recache?

### ISSUE THREAD

**Issue by burrbull** [Swatinem/rust-cache#46]
Did not find in docs.

**Comment by Kryptos-FR** [comment]
Can we have a cache stale duration or something instead?

I have some repo where cargo.lock is not versioned (for various reasons) which causes the cache to become useless after a while but since the hash never changes it doesn't get re-cached. After a max time or a parameter that automatically force a recache would help.

Note that this would also be useful when using `cargo.lock`: a cache from a CI job triggered by a successful merge to the main branch could serve as a "golden" cache for other CI jobs in features branch to use.

**Comment by Swatinem** [comment]
The rustc version is used as part of the cache key. So in theory if you use stable rust, you get a new version every 6 weeks ;-)

Otherwise there is no timing that could be used there.

**Comment by Swatinem** [comment]
GitHub also has an API now that you can use to list and clean your caches: https://docs.github.com/en/rest/actions/cache
