### ISSUE TITLE
Is running `cargo generate-lockfile` recommended for repositories without Cargo.lock?

### ISSUE THREAD

**Issue by jpmckinney** [Swatinem/rust-cache#93]
I notice that e.g. https://github.com/rust-lang/rust-clippy/blob/master/.github/workflows/deploy.yml does this. If so, it might be a good point to add to the docs.

**Comment by Swatinem** [comment]
In that case you might as well just check in your lockfile. The `generate-lockfile` command needs to fetch the whole cargo index, which this action would cache, and which is particularly slow as of late.

Not only that, it gives you all the latest dependencies, so the build cache would also be outdated more often.

I believe it can happen that due to the cache, it will sometimes use older cached dependency versions rather than the absolute latest. In that case just run a `cargo update / generate-lockfile` after the cache at least restored an index snapshot.

**Comment by jpmckinney** [comment]
That makes a lot of sense. I'll use `cargo update` after this action (that way, if my crate breaks on the latest versions of dependencies, I'll find out – and otherwise I'll get a faster build). Thank you!
